<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Machine Learning - 2301CS621</b></center>

<center><b><h1>Lab - 3</b></center>
<b><h3>Mudit Bhatt</b>   
<b><h1>23010101607</b> 
<pre>    

# NumPy Exercises
## We'll start off with a few simple tasks

## import numpy as np

In [1]:
import numpy as np

## Create an array of 10 zeros

In [2]:
zeros_array = np.zeros(10)

print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Create an array of 10 ones

In [3]:
ones_array = np.ones(10)

print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Create an array of 10 fives

In [5]:
fives_array = np.full(10, 5)

print(fives_array)

[5 5 5 5 5 5 5 5 5 5]


## Create an array of the integers from 10 to 50

In [6]:
int_array = np.arange(10, 51)

print(int_array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


## Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
matrix = np.arange(9).reshape(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Create a 3x3 identity matrix

In [8]:
identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Create following matrix  = <br/>
<pre>array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])</pre>

In [9]:
matrix = np.arange(1, 26).reshape(5, 5)

print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


## Output should be =
<pre>array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])</pre>

In [10]:
matrix = np.arange(1, 26).reshape(5, 5)

submatrix = matrix[2:, 1:]

print(submatrix)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


## Output should be = <br/>
<pre>array([[ 2],
       [ 7],
       [12]])</pre>

In [13]:
matrix = np.arange(1, 26).reshape(5, 5)

submatrix = matrix[0:3, 1:2]

print(submatrix)

[[ 2]
 [ 7]
 [12]]


## Output should be =  <br/>
<pre>array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])</pre>

In [14]:
matrix = np.arange(1, 26).reshape(5, 5)

submatrix = matrix[3:, :]

print(submatrix)

[[16 17 18 19 20]
 [21 22 23 24 25]]


# Great Job! You’re Halfway Through 🚀

## Step 1. Import the necessary libraries

In [30]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


## Step 2. Import the dataset

In [16]:
data = pd.read_csv('50_Startups.csv')

print(data.head())

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94


## Step 3 . Check the State Column

In [17]:
print(data['State'])

0       New York
1     California
2        Florida
3       New York
4        Florida
5       New York
6     California
7        Florida
8       New York
9     California
10       Florida
11    California
12       Florida
13    California
14       Florida
15      New York
16    California
17      New York
18       Florida
19      New York
20    California
21      New York
22       Florida
23       Florida
24      New York
25    California
26       Florida
27      New York
28       Florida
29      New York
30       Florida
31      New York
32    California
33       Florida
34    California
35      New York
36       Florida
37    California
38      New York
39    California
40    California
41       Florida
42    California
43      New York
44    California
45      New York
46       Florida
47    California
48      New York
49    California
Name: State, dtype: object


## Step 4 . Splitting dataset in to input and output

In [18]:
x = data[['R&D Spend']].values.reshape(-1, 1) 
y = data['Profit']

print("Input Features (x):")
print(x[:5])  

print("\nOutput Target (y):")
print(y[:5])  

Input Features (x):
[[165349.2 ]
 [162597.7 ]
 [153441.51]
 [144372.41]
 [142107.34]]

Output Target (y):
0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64


## Step 5 . Convert state Column into Numeric Column

## Step 5.1 .  Import  ColumnTransformer

In [23]:
from sklearn.compose import ColumnTransformer

## Step 5.2 .  Import  OneHotEncoder

In [24]:
from sklearn.preprocessing import OneHotEncoder


## Step 5.3 .  Perform Transformation

In [25]:
column_transformer = ColumnTransformer(
    transformers=[
        ('state', OneHotEncoder(), ['State'])  
    ], 
    remainder='passthrough'  
)

data_transformed = column_transformer.fit_transform(data)

data_transformed_df = pd.DataFrame(data_transformed, columns=column_transformer.get_feature_names_out())

print(data_transformed_df.head())

   state__State_California  state__State_Florida  state__State_New York  \
0                      0.0                   0.0                    1.0   
1                      1.0                   0.0                    0.0   
2                      0.0                   1.0                    0.0   
3                      0.0                   0.0                    1.0   
4                      0.0                   1.0                    0.0   

   remainder__R&D Spend  remainder__Administration  \
0             165349.20                  136897.80   
1             162597.70                  151377.59   
2             153441.51                  101145.55   
3             144372.41                  118671.85   
4             142107.34                   91391.77   

   remainder__Marketing Spend  remainder__Profit  
0                   471784.10          192261.83  
1                   443898.53          191792.06  
2                   407934.54          191050.39  
3                   

## Step 6 . Dummy variable trap

In [27]:
column_transformer = ColumnTransformer(
    transformers=[
        ('state', OneHotEncoder(drop='first'), ['State']) 
    ], 
    remainder='passthrough'  
)

data_transformed = column_transformer.fit_transform(data)

data_transformed_df = pd.DataFrame(data_transformed, columns=column_transformer.get_feature_names_out())

print(data_transformed_df.head())

   state__State_Florida  state__State_New York  remainder__R&D Spend  \
0                   0.0                    1.0             165349.20   
1                   0.0                    0.0             162597.70   
2                   1.0                    0.0             153441.51   
3                   0.0                    1.0             144372.41   
4                   1.0                    0.0             142107.34   

   remainder__Administration  remainder__Marketing Spend  remainder__Profit  
0                  136897.80                   471784.10          192261.83  
1                  151377.59                   443898.53          191792.06  
2                  101145.55                   407934.54          191050.39  
3                  118671.85                   383199.62          182901.99  
4                   91391.77                   366168.42          166187.94  


## Step 7 Splitting dataset in to Train and Test

In [29]:
X = data.drop('Profit', axis=1) 
y = data['Profit']  

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training data shape (X_train, y_train): {X_train.shape}, {y_train.shape}")
print(f"Test data shape (X_test, y_test): {X_test.shape}, {y_test.shape}")

Training data shape (X_train, y_train): (40, 4), (40,)
Test data shape (X_test, y_test): (10, 4), (10,)


## Step 8  Import LinearRegression model from linear_model family 

In [34]:
model = LinearRegression()



## Step 9  Fit the data

In [38]:
column_transformer = ColumnTransformer(
    transformers=[
        ('state', OneHotEncoder(drop='first'), ['State'])  
    ], 
    remainder='passthrough'  
)

X_transformed = column_transformer.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_transformed, y, test_size=0.2, random_state=42)

model = LinearRegression()

model.fit(X_train, y_train)

print("Model coefficients:", model.coef_)
print("Model intercept:", model.intercept_)

Model coefficients: [ 9.38793006e+02  6.98775997e+00  8.05630064e-01 -6.87878823e-02
  2.98554429e-02]
Model intercept: 54028.03959405866


## Step 10  Predict the data

In [39]:
y_pred = model.predict(X_test)

print("Predictions:", y_pred)

Predictions: [126362.87908252  84608.45383643  99677.49425155  46357.46068582
 128750.48288497  50912.41741905 109741.350327   100643.24281644
  97599.275746   113097.42524437]


## Step 11  Display Result

In [40]:
result = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})

print("Actual vs Predicted Results:\n", result)

Actual vs Predicted Results:
        Actual      Predicted
13  134307.35  126362.879083
39   81005.76   84608.453836
30   99937.59   99677.494252
45   64926.08   46357.460686
17  125370.37  128750.482885
48   35673.41   50912.417419
26  105733.54  109741.350327
25  107404.34  100643.242816
32   97427.84   97599.275746
19  122776.86  113097.425244
